from quii_helper.config import constants

HOST = ""
CLOUD_ACCOUNT = constants.CLOUD_ACCOUNT
CLOUD_PASSWORD = constants.CLOUD_PASSWORD
DEVICE_ID = constants.DEVICE_ID
AUTH_CODE = constants.AUTH_CODE
DEVICE_PASSWORD = constants.DEVICE_PASSWORD
TLS_VERIFY = constants.TLS_VERIFY
NC = "0123456789abcdef0123456789abcdef"

IS_HS_DEVICE = None

QUII_HOST = HOST
QUII_PORT = 34567
QUII_AP = 2
QUII_USE_FORWARDED_RELAY = True
QUII_RELAY_HOST = "127.0.0.1"
QUII_RELAY_PORT = 45723
QUII_RELAY_CHANNEL = 1
QUII_RELAY_STREAM = 1
QUII_RELAY_NEWCN = False
QUII_CHANNEL_CANDIDATES = [0, 1, 2, 3]
QUII_STREAM_CANDIDATES = [1, 2, 0]
QUII_USE_INNER = False
QUII_NEWCN_CANDIDATES = [False, True]
QUII_RUN_PROBE = True
QUII_NUM_MESSAGES = 80
QUII_EXTRACT_STREAM = True
QUII_RENDER_SNAPSHOT = True
QUII_KEEP_RAW_H264 = False
QUII_PRINT_FULL_PROBE = False

RUN_DEVICE_CGI_PROBES = False
RUN_CLOUD_FLOW = True
