import importlib

import quii_helper

ROOT_PUBLIC_API = [
    "AssetMissingError",
    "AutonomousConfig",
    "Camera",
    "CameraCaptureError",
    "CameraCaptureResult",
    "CameraDeviceAllInfo",
    "CameraDeviceAlarmChannel",
    "CameraDeviceAlarmChannelInfo",
    "CameraDeviceAlarmInputChannel",
    "CameraDeviceAlarmInputInfo",
    "CameraDeviceAlarmMotionDetectionInfo",
    "CameraDeviceAlarmScheduleDay",
    "CameraDeviceAlarmScheduleInfo",
    "CameraDeviceAlarmScheduleSlot",
    "CameraDeviceAlarmVideoLostInfo",
    "CameraDeviceAlarmVideoShelterInfo",
    "CameraDeviceAlarmDetailChannelInfo",
    "CameraDeviceAlarmDetailInfo",
    "CameraDeviceAlarmDetailIntervalInfo",
    "CameraDeviceAlarmDetailLevelInfo",
    "CameraDeviceAlarmDetailRegionInfo",
    "CameraDeviceAlarmDetailSmartFilterInfo",
    "CameraDeviceAlarmStatusInfo",
    "CameraDeviceAudioSessionInfo",
    "CameraDeviceAudioVolumeInfo",
    "CameraDeviceAudioVolumeRange",
    "CameraDeviceAttachmentAlarm",
    "CameraDeviceAttachmentChannel",
    "CameraDeviceAttachmentElevator",
    "CameraDeviceAttachmentInfo",
    "CameraDeviceAttachmentLock",
    "CameraDeviceAttachmentProfile",
    "CameraDeviceAttachmentSmartSwitch",
    "CameraDeviceCapabilitiesInfo",
    "CameraDeviceCityCoordinateInfo",
    "CameraDeviceCommandStatus",
    "CameraDeviceBabysitterStateInfo",
    "CameraDeviceFloodlightInfo",
    "CameraDeviceFloodlightScheduleDayInfo",
    "CameraDeviceFloodlightScheduleInfo",
    "CameraDeviceFloodlightSchedulePlanInfo",
    "CameraDeviceFloodlightScheduleTimeInfo",
    "CameraDeviceFloodlightSwitchInfo",
    "CameraDeviceFpsChannelInfo",
    "CameraDeviceFpsInfo",
    "CameraDeviceGeneralInfo",
    "CameraDeviceHardwareInfo",
    "CameraDeviceHumanTraceInfo",
    "CameraDeviceInfo",
    "CameraIotCommandSupportInfo",
    "CameraDeviceLanInfo",
    "CameraDeviceLightInfo",
    "CameraDeviceLightItemInfo",
    "CameraDeviceLightRoomInfo",
    "CameraDeviceMoveDetectionInfo",
    "CameraDeviceMotionDetectionInfo",
    "CameraDeviceNetworkBaseAbility",
    "CameraDeviceNetworkBaseInfo",
    "CameraDeviceNetworkInfo",
    "CameraDeviceNetworkTransferPolicy",
    "CameraDeviceJsonFpsModeInfo",
    "CameraDeviceLockInfo",
    "CameraDeviceLockStatusInfo",
    "CameraDeviceLockTimeInfo",
    "CameraDevicePirConfigInfo",
    "CameraDevicePirScheduleDayInfo",
    "CameraDevicePirScheduleSlotInfo",
    "CameraDeviceProductInfo",
    "CameraDeviceQrCodeInfo",
    "CameraDeviceRecordAlarmInfo",
    "CameraDeviceRecordConfigInfo",
    "CameraDeviceRecordFileInfo",
    "CameraDeviceRecordListInfo",
    "CameraDeviceRecordMessageInfo",
    "CameraDeviceRecordScheduleTime",
    "CameraDeviceRecordSessionInfo",
    "CameraDevicePtzPreset",
    "CameraDevicePtzPresetInfo",
    "CameraDevicePtzStateInfo",
    "CameraDeviceProfile",
    "CameraDeviceScreenFlipInfo",
    "CameraDeviceShadowInfo",
    "CameraDeviceShadowState",
    "CameraDeviceShadowSwitchState",
    "CameraDeviceSmartLightInfo",
    "CameraDeviceSmartLightItem",
    "CameraDeviceSmartSwitchChannelInfo",
    "CameraDeviceSmartSwitchInfo",
    "CameraDeviceSmartSwitchItemInfo",
    "CameraDeviceSmartSwitchRoomInfo",
    "CameraDeviceThirdPartyPushInfo",
    "CameraDeviceThirdPartyPushScheduleDayInfo",
    "CameraDeviceThirdPartyPushScheduleSlotInfo",
    "CameraDeviceSoundLightChannelInfo",
    "CameraDeviceSoundLightInfo",
    "CameraDeviceStorageInfo",
    "CameraDeviceStreamKeyInfo",
    "CameraDeviceTfCardDiskInfo",
    "CameraDeviceTfCardInfo",
    "CameraDeviceStreamProfile",
    "CameraDeviceTimeInfo",
    "CameraDeviceTimeTitleInfo",
    "CameraDeviceUpgradeProcessInfo",
    "CameraDeviceUpgradeStatusInfo",
    "CameraDeviceUpgradeVersionInfo",
    "CameraDeviceVideoChannelInfo",
    "CameraDeviceVideoConfigInfo",
    "CameraDeviceVideoSwitchInfo",
    "CameraDeviceVoiceFileInfo",
    "CameraDeviceVoiceMessageInfo",
    "CameraDeviceWifiListInfo",
    "ConfigurationError",
    "LanDeviceCandidate",
    "MediaRenderError",
    "PreviewCaptureSettings",
    "QuiiConnectionError",
    "QuiiHelperError",
    "RuntimeCredentials",
]

ROOT_INTERNAL_NAMES = [
    "CameraConnector",
    "CameraPreviewApplication",
    "CameraPreviewSession",
    "DirectKcpQuiiTunnel",
    "MqttP2PBootstrap",
    "P2PConnectRequest",
    "P2PConnectResponse",
    "PreviewArtifactManager",
    "PreviewCapturePipeline",
    "PreviewOutputWriter",
    "PreviewPacketProcessor",
    "PreviewPipelineFactory",
    "QuiiClient",
    "RbUdpQuiiTunnel",
    "TcpLiveProbeCapture",
    "TcpProbeRunner",
    "TcpSocketTransport",
    "TunnelPacketStream",
    "aes_cbc_crypt",
    "assemble_h264_stream_from_messages",
    "build_live_keepalive_packet",
    "build_live_play_packet",
    "build_live_setup_packet",
    "create_request_session_id",
    "create_session_flag",
    "decode_quii_blob",
    "open_direct_preview",
    "write_h264_stream",
]

EXPORT_PACKAGES = (
    "quii_helper",
    "quii_helper.cloud",
    "quii_helper.device",
    "quii_helper.device.json_cgi",
    "quii_helper.diagnostics",
    "quii_helper.diagnostics.wrapped",
    "quii_helper.devtools",
    "quii_helper.direct",
    "quii_helper.io",
    "quii_helper.media",
    "quii_helper.preview",
    "quii_helper.protocols",
    "quii_helper.protocols.mqtt",
    "quii_helper.protocols.p2p",
    "quii_helper.protocols.quii",
    "quii_helper.protocols.rbudp",
    "quii_helper.protocols.tcp",
    "quii_helper.protocols.ust",
    "quii_helper.streaming",
    "quii_helper.streaming.h264",
    "quii_helper.streaming.rtp",
    "quii_helper.streaming.rtsp",
    "quii_helper.camera.device_json_cgi",
)


class PublicApiTests:
    def test_root_exported_symbols_import(self) -> None:
        failures = []
        for name in quii_helper.__all__:
            try:
                getattr(quii_helper, name)
            except Exception as exc:  # pragma: no cover - failure details
                failures.append((name, type(exc).__name__, str(exc)))

        assert [] == failures

    def test_root_all_matches_static_public_api(self) -> None:
        assert ROOT_PUBLIC_API == quii_helper.__all__

    def test_export_packages_import_all_symbols(self) -> None:
        failures = []
        for package_name in EXPORT_PACKAGES:
            package = importlib.import_module(package_name)
            for name in package.__all__:
                try:
                    getattr(package, name)
                except Exception as exc:  # pragma: no cover - failure details
                    failures.append(
                        (package_name, name, type(exc).__name__, str(exc))
                    )

        assert [] == failures

    def test_root_package_uses_static_exports(self) -> None:
        assert not hasattr(quii_helper, "__getattr__")

    def test_root_package_does_not_export_internal_api(self) -> None:
        for name in ROOT_INTERNAL_NAMES:
            assert not hasattr(quii_helper, name)

    def test_camera_high_level_methods_exist(self) -> None:
        camera_cls = quii_helper.Camera
        for method_name in (
            "capture",
            "snapshot",
            "save_video",
            "record",
            "serve_rtsp",
            "discover_lan_devices",
            "get_device_info",
            "get_device_shadow_info",
            "get_iot_command_support",
            "get_alarm_channel_info",
            "get_alarm_input_info",
            "get_alarm_motion_detection_info",
            "get_alarm_motion_detection_schedule",
            "get_alarm_video_lost_schedule",
            "get_alarm_video_shelter_schedule",
            "get_alarm_input_schedule",
            "get_alarm_detail_info",
            "get_alarm_status_info",
            "get_alarm_video_lost_info",
            "get_alarm_video_shelter_info",
            "get_device_attachment_info",
            "get_motion_detection_info",
            "get_human_trace_info",
            "get_move_detection_info",
            "get_fps_info",
            "get_json_fps_mode_info",
            "get_audio_volume_info",
            "get_audio_session_info",
            "get_hardware_info",
            "get_light_info",
            "get_babysitter_state_info",
            "get_pir_config_info",
            "get_third_party_push_info",
            "get_smart_switch_info",
            "get_lock_status_info",
            "get_floodlight_switch_info",
            "get_floodlight_schedule_info",
            "get_city_coordinate_info",
            "get_voice_message_info",
            "get_ptz_state",
            "get_ptz_presets",
            "get_smart_light_info",
            "get_sound_light_info",
            "get_device_profile",
            "get_device_all_info",
            "get_product_info",
            "get_storage_info",
            "get_tf_card_info",
            "get_time_info",
            "get_stream_key_info",
            "get_qr_code_info",
            "get_record_alarm_info",
            "get_record_config_info",
            "list_record_files",
            "get_record_message_info",
            "get_record_session_info",
            "get_wifi_list",
            "get_screen_flip_info",
            "get_video_switch_info",
            "get_time_title_info",
            "get_network_info",
            "get_network_base_info",
            "get_network_interfaces",
            "get_system_general_info",
            "get_system_capabilities",
            "get_upgrade_version_info",
            "get_upgrade_status_info",
            "get_upgrade_process_info",
            "get_video_config",
            "get_video_channels",
            "get_stream_profiles",
        ):
            assert callable(getattr(camera_cls, method_name, None))
